<a href="https://colab.research.google.com/github/AquilaDream/AULA_SENAI-01/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
# PUXANDO UMA TABELA DO EXCEL EM UMA ARRAY COMO PLANILHA

import numpy as np
goiaba_csv = np.genfromtxt('/content/goiaba.csv', delimiter=',')

In [10]:
goiaba_csv

array([[23., 29., 95.],
       [24., 20., 21.],
       [18., 23., 16.],
       [19., 30., 36.]])

In [12]:
pesos = np.array([0.4, 0.2, 0.8])

In [13]:
rendimento = goiaba_csv @ pesos
rendimento

array([91. , 30.4, 24.6, 42.4])

In [18]:
import numpy as np

resultado = np.concatenate((goiaba_csv, rendimento.reshape(4, 1)), axis=1)
resultado

array([[23. , 29. , 95. , 91. ],
       [24. , 20. , 21. , 30.4],
       [18. , 23. , 16. , 24.6],
       [19. , 30. , 36. , 42.4]])

In [19]:
#AGORA É SO SALVAR

np.savetxt('goiaba_resultado.csv',
           resultado,
           fmt='%.2f',
           delimiter=',',
           header='temperatura, precipitação, umidade, rendimento',
           comments="")